name: CI

on: push 

jobs:
  linting:
    runs-on: ${matrix.os}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        
    steps:
      - name : code Checkout
        uses: actions/checkout@v2

      - name: setup python 
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          
      - name : install flake8
        run : |
          python -m pip install --upgrade pip
          pip install flake8


      - name : run flake8
        run : |
          flake8 app.py


